#
###################################
# Site wide configuration
####################################
#
title: Yash Shah's blog
email:
description: My blog for things I find interesting.
url: https://yashshah1.github.io/blog
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone: Asia/Calcutta
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
permalink: /articles/:year-:month/:title
google_analytics: UA-167434478-1

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Yash Shah
  # avatar: leonids-logo.png
  job: "A set of random thoughts (and rants)"
  bio: "A curious final year CE student"
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: yashshah1
  gitlab: yashshah1
  stackoverflow: 11362183/yash-shah
  linkedin: yashshah13
  skype: #username
  xing: #username
  instagram: itsmeyashshah
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

theme: jekyll-theme-slate
